#!/bin/sh
set -e
case "$1" in
    remove|purge)
        if [ -d /run/systemd/system ]; then
            systemctl daemon-reload
        fi
        dpkg-trigger --no-await kalinka-server-restart || true
        ;;
esac
